### ISSUE TITLE
"Could not set 'directory' on ensure: Permission denied" errors with rspec-puppet > 1.0.1 + puppet 3.7.3 future parser

### ISSUE THREAD

**Issue by jhoblitt** [domcleal/rspec-puppet-augeas#15]
I made a big push yesterday to add the future parser to the travis matrix of all of my published puppet forge modules and discovered that the two modules that use `rspec-puppet-augeas` fail under the future parser with error messages like: `Evaluation Error: Use of 'import' has been discontinued in favor of a manifest directory`.  

Direct links to travis runs for both modules with future parser errors:

https://travis-ci.org/jhoblitt/puppet-mdadm/builds/41427168
https://travis-ci.org/jhoblitt/puppet-autofsck/builds/41423244

Example (truncated) rspec errors with future parser enabled:

```
[future_parser] ~/github/puppet-mdadm $ FUTURE_PARSER="yes" bundle exec rake spec
HEAD is now at f8ce04a Merge branch 'release/master/three_dot_oh_dot_oh'
/home/jhoblitt/.rvm/rubies/ruby-2.1.5/bin/ruby -S rspec spec/unit/classes/mdadm_params_spec.rb spec/unit/classes/mdadm_spec.rb spec/unit/facts/mdadm_arrays_spec.rb spec/unit/facts/mdadm_spec.rb spec/unit/facts/mdadmversion_spec.rb --color
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF..........

Failures:

  1) mdadm::params for osfamily RedHat 6.x 
     Failure/Error: it { should contain_class('mdadm::params') }
     Puppet::Error:
       Evaluation Error: Use of 'import' has been discontinued in favor of a manifest directory. See http://links.puppetlabs.com/puppet-import-deprecation at line 2:1 on node shinything.lan
     # ./spec/unit/classes/mdadm_params_spec.rb:15:in `block (4 levels) in <top (required)>'

  2) mdadm::params for osfamily RedHat 5.x 
     Failure/Error: it { should contain_class('mdadm::params') }
     Puppet::Error:
       Evaluation Error: Use of 'import' has been discontinued in favor of a manifest directory. See http://links.puppetlabs.com/puppet-import-deprecation at line 2:1 on node shinything.lan
     # ./spec/unit/classes/mdadm_params_spec.rb:21:in `block (4 levels) in <top (required)>'

  3) mdadm::params for osfamily RedHat 4.x should fail
     Failure/Error: expect { should contain_class('mdadm::params') }.
       expected Puppet::Error with message matching /not supported on Scientific 4/, got #<Puppet::Error: Evaluation Error: Use of 'import' has been discontinued in favor of a manifest directory. See http://links.puppetlabs.com/puppet-import-deprecation at line 2:1 on node shinything.lan> with backtrace:
         # ./spec/unit/classes/mdadm_params_spec.rb:28:in `block (5 levels) in <top (required)>'
         # ./spec/unit/classes/mdadm_params_spec.rb:28:in `block (4 levels) in <top (required)>'
     # ./spec/unit/classes/mdadm_params_spec.rb:28:in `block (4 levels) in <top (required)>'

  4) mdadm::params unsupported osfamily should fail
     Failure/Error: expect { should contain_class('mdadm::params') }.
       expected Puppet::Error with message matching /not supported on Debian/, got #<Puppet::Error: Evaluation Error: Use of 'import' has been discontinued in favor of a manifest directory. See http://links.puppetlabs.com/puppet-import-deprecation at line 2:1 on node shinything.lan> with backtrace:
         # ./spec/unit/classes/mdadm_params_spec.rb:43:in `block (4 levels) in <top (required)>'
         # ./spec/unit/classes/mdadm_params_spec.rb:43:in `block (3 levels) in <top (required)>'
     # ./spec/unit/classes/mdadm_params_spec.rb:43:in `block (3 levels) in <top (required)>'
...
```

**Comment by domcleal** [comment]
0.4.0's released now which should fix the permissions problem, just leaving the multi-libdir case as the rspec-puppet PR's still open.

**Comment by jhoblitt** [comment]
I think this is real progress, I'm down to errors which I assume are bubbling up from trying to write to /dev/null.

```
     Failure/Error: should execute.with_change
     NoMethodError:
       Could not create resources for managing Puppet's files and directories in sections [:main]: undefined method `exists?' for nil:NilClass
       undefined method `exists?' for nil:NilClass
     Shared Example Group: "debian" called from ./spec/classes/autofsck_spec.rb:77
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/type/user.rb:382:in `exists?'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings.rb:800:in `service_user_available?'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings/file_setting.rb:52:in `safe_to_use_settings_value?'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings/file_setting.rb:43:in `value'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings/file_setting.rb:106:in `owner'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings/file_setting.rb:160:in `to_resource'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings.rb:916:in `block in to_catalog'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings.rb:912:in `each'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings.rb:912:in `to_catalog'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/settings.rb:982:in `use'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/util/storage.rb:45:in `load'
     # ./.bundle/ruby/2.1.0/gems/puppet-3.7.5/lib/puppet/resource/catalog.rb:163:in `apply'
     # ./.bundle/ruby/2.1.0/gems/rspec-puppet-augeas-0.4.0/lib/rspec-puppet-augeas/fixtures.rb:51:in `apply'
     # ./.bundle/ruby/2.1.0/gems/rspec-puppet-augeas-0.4.0/lib/rspec-puppet-augeas/resource.rb:17:in `initialize'
     # ./.bundle/ruby/2.1.0/gems/rspec-puppet-augeas-0.4.0/lib/rspec-puppet-augeas/example/run_augeas_example_group.rb:69:in `new'
     # ./.bundle/ruby/2.1.0/gems/rspec-puppet-augeas-0.4.0/lib/rspec-puppet-augeas/example/run_augeas_example_group.rb:69:in `subject'
     # ./spec/classes/autofsck_spec.rb:32:in `block (4 levels) in <top (required)>'
```
